CREATE DATABASE iot_db;
\c iot_db

CREATE TABLE "sensor_logs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "timestamp_real" timestamp,
  "timestamp_up" timestamp NOT NULL,
  "temperature" text,
  "humidity" text,
  "soil_moisture" text,
  "PUMP_state" text,
  "MODE_state" text,
  "Message" text,
  "Score" text,
  "device_id" text
);

CREATE USER iot_user WITH PASSWORD 'iot_password';
GRANT ALL PRIVILEGES ON TABLE sensor_logs TO iot_user;
GRANT USAGE, SELECT ON SEQUENCE sensor_logs_id_seq TO iot_user;