-- DB/DB.sql (sau khi chỉnh sửa — KHÔNG có CREATE DATABASE hay \c)

CREATE TABLE IF NOT EXISTS "sensor_logs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "timestamp_real" timestamp,
  "timestamp_up" timestamp NOT NULL,
  "temperature" text,
  "humidity" text,
  "soil_moisture" text,
  "PUMP_state" text,
  "MODE_state" text,
  "Message" text,
  "Score" text,
  "device_id" text,
  "latency" int,
  "trigger_source" text
);

CREATE TABLE IF NOT EXISTS device_credentials (
  device_id text PRIMARY KEY,
  password  text NOT NULL
);

DO $$
BEGIN
  CREATE USER iot_user WITH PASSWORD '004232';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

GRANT ALL PRIVILEGES ON TABLE sensor_logs TO iot_user;
GRANT USAGE, SELECT ON SEQUENCE sensor_logs_id_seq TO iot_user;
GRANT ALL PRIVILEGES ON TABLE device_credentials TO iot_user;